### ISSUE TITLE
needle test with llama2

### ISSUE THREAD

**Issue by MarsMeng1994** [HKUNLP/ChunkLlama#11]
<img width="1003" alt="image" src="https://github.com/HKUNLP/ChunkLlama/assets/24523981/f7ec06e2-e896-40a3-ac0f-bc1bb4586ce3">

<img width="503" alt="image" src="https://github.com/HKUNLP/ChunkLlama/assets/24523981/3e0c72fe-f902-4233-ab8a-a1b3aaf4c41a">

9k is going to not work

model: Llama-2-7b-hf
transformers: 4.37.2
torch: 2.0.1
flash-attn: 2.5.2

my cmd:
python retrieve_needle.py --max_length 192k --model llama --dca

**Comment by MarsMeng1994** [comment]
my cmd:
python retrieve_needle.py --max_length 192k --model llama --dca

**Comment by ChenxinAn-fdu** [comment]
Hi! Thank you for this issue. 
Pls set the `--pretraining_length 4096` for Llama2. 
`python retrieve_needle.py --max_length 192k --pretraining_length 4096 --model llama --dca`
The default value is set to 32k due to my latest experiment on Mistral. Sorry for the inconvenience.

**Comment by MarsMeng1994** [comment]
> Hi! Thank you for this issue. Pls set the `--pretraining_length 4096` for Llama2. `python retrieve_needle.py --max_length 192k --pretraining_length 4096 --model llama --dca` The default value is set to 32k due to my latest experiment on Mistral. Sorry for the inconvenience.

sorry, i forget to say but my --pretraining_length is already 4096 
<img width="985" alt="image" src="https://github.com/HKUNLP/ChunkLlama/assets/24523981/fb160a08-5e95-4e29-a588-20800c35818e">

**Comment by MarsMeng1994** [comment]
oh, i find the problem 
<img width="463" alt="image" src="https://github.com/HKUNLP/ChunkLlama/assets/24523981/934a69ee-7c04-47b5-869f-905a35115c0d">
it default use replace_with_chunkmistral

**Comment by ChenxinAn-fdu** [comment]
Hahaha I think so!
Does it work now?

**Comment by ChenxinAn-fdu** [comment]
I will close this issue for now. Should you have any further questions or concerns, please don't hesitate to reopen it.
