### ISSUE TITLE
Does it support the Qwen1.5-72B-Chat-GPTQ-Int4 quantized model?

### ISSUE THREAD

**Issue by huliangbing** [HKUNLP/ChunkLlama#14]
Great work!
Does it support the Qwen1.5-72B-Chat-GPTQ-Int4 quantized model?

**Comment by ChenxinAn-fdu** [comment]
Thank you for this issue! 

I think it can support int4/8 quantized models, but actually I have not experimented with qwen1.5-int4. The code works for all Qwen models with fp16/bf16 (`chunkqwen_attn_replace.py`).

**Comment by huliangbing** [comment]
Thank you for your so quick reply.
If I use qwen1.5-int4/8 models,  what should I do?

**Comment by ChenxinAn-fdu** [comment]
I am not an expert in quantized models. Maybe you can directly use the code and provide some detailed information like terminal outputs.

**Comment by huliangbing** [comment]
I will have a try.
